### PR TITLE
Feat: new peering flow

### PR DESCRIPTION
**Pull request by sharafian**
This new version is designed to do a peering flow with plugin virtual v7. The flow to configure an instance of ILP kit will now be:

1. run `ilp-kit-config configure env.list` to create `env.list` and put basic settings in. It won't ask you for any credentials on other ledgers or any peer addresses.
2. run `ilp-kit-config key`, and enter a secret to create a public key. Put this public key so that people who want to peer with you can find it.

You no longer have to modify `CONNECTOR_PEERS` or `LEDGER_RECOMMENDED_CONNECTORS` Now when you want to peer with somebody:

1. Find their public key, and copy it down.
2. Agree on an MQTT broker.
3. You'll also want to decide on a maximum balance you'll hold on this trust-line.
4. run `ilp-kit-config peer-add env.list`. Enter your secret, their public key, the MQTT broker, and the trust-line currency. Now the `CONNECTOR_LEDGERS` field in your config will include an additional trust-line. You can also give the trust-line a nickname, to reference it later.

If you want to view your current trust-lines, you can run `ilp-kit-config peer-list env.list`. To remove a trust-line, you can use `ilp-kit-config peer-remove env.list`, which will list your trustlines and prompt you to remove one of them.

### CODE REVIEW

**Comment by vhpoet** [comment]
Couple of suggestions. _None of these are deal breakers_.

- How about having `env.list` as a default? so if I don't specify a file name it uses `env.list`. 
- (minor) How about using git style `peer add`, `peer remove` and `peer list` instead of `peer-add`, `peer-remove`, `peer-list`.
- In the future we could have a prefix for the env variables or properties specified in the file that are only used by the configurator tool.

Everything else looks great.

**Comment by sharafian** [comment]
How would you feel about `configure`, `peer`, `unpeer`, and `list`?

**Comment by vhpoet** [comment]
@sharafian sounds better then `peer-add`, `peer-remove`.

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
